### ISSUE TITLE
complection misses $var$var

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#12]
Name $dd$ee missed in list

![var 2](https://user-images.githubusercontent.com/4154978/29860075-6b9cd48a-8d6d-11e7-8402-9ba942607c81.png)

**Comment by TomBraider42** [comment]
I don't think $var$var is a correct variable name. Never see it and AutoIt gives an error (cuda_lint_autoit).
![clipboard 1](https://user-images.githubusercontent.com/5128016/29860535-ab03c202-8d66-11e7-9da5-818c186b76c3.png)

**Comment by Alexey-T** [comment]
Ok, I see
