### ISSUE TITLE
Plugin with sidebar

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#13]
Hi, do you make plugin with sidebar support. can I see it or screenshots?

**Comment by TomBraider42** [comment]
Don't understand. The AutoIt Helper doesn't have/need sidebar support.

**Comment by Alexey-T** [comment]
It's about another plugin (not AutoIt)

**Comment by TomBraider42** [comment]
Ok, what are you gonna do? You mean my questions about the slider?
I have my own project manager because i needs another work flow. With included code tree.
![sidebar](https://user-images.githubusercontent.com/5128016/33567704-57b60574-d924-11e7-8f5c-864c29f3c9d2.PNG)

**Comment by Alexey-T** [comment]
Is plugin ready for other ppl?

**Comment by TomBraider42** [comment]
Not at the moment. There are some dependencies. Before publishing i have to make it more "user compatible". Also the code tree uses my own file parser (only a few formats), not the lexer files.
BTW: is there a way to add icons to the entries of a context menu?

**Comment by Alexey-T** [comment]
Menu_proc() don't support it yet [will think about it]

**Comment by Alexey-T** [comment]
Btw, dependencies: you may copy all Py libs to plugin folder , and load them via

```
import sys
import os
sys.path.append(os.path.dirname(__file__))
import jedi
```

**Comment by Alexey-T** [comment]
API menu_proc can now add icons (see the wiki)

**Comment by TomBraider42** [comment]
http://wiki.freepascal.org/CudaText_API#menu_proc
not jet updated?

**Comment by Alexey-T** [comment]
ops; updated now
http://wiki.freepascal.org/index.php?title=CudaText_API&action=history
