### ISSUE TITLE
Refact

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#15]
if ed_self.get_prop(PROP_LEXER_CARET) == 'AutoIt':

You have 3+ such lines
Pls make function. Also- better use PROP_LEXER_FILE (lexer for file).

**Comment by Alexey-T** [comment]
with install.inf

```

[item1]
section=events
events=on_open,on_change_slow,on_save,on_func_hint,on_complete,on_goto_def
lexers=AutoIt
```

check is not needed.

**Comment by TomBraider42** [comment]
changed in 2018.02.02
