### ISSUE TITLE
Can update via fork?

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#21]
I want to update plugin- add insertion of func parameters on choosing the function, like in ST3 plugin.
will you accept pull req?
will you change plugin by urself?

**Comment by TomBraider42** [comment]
I don't understand your question. What you want to change?
Just post a request and i will check it.

**Comment by Alexey-T** [comment]
patch will be ready after few days. Ok, i wait.

**Comment by Alexey-T** [comment]
@OlehL made a fork and big rework of code.
I release it as an update for plugin.
https://github.com/OlehL/cuda_autoit_helper

**Comment by Alexey-T** [comment]
Pls consider using Oleh's code - you can get PR from his repo (Github has button on site)

**Comment by Alexey-T** [comment]
Any update on Side panel plugin (not released)?
