### ISSUE TITLE
Autoit.acp

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#3]
Autoit lexer has autoit.acp fle 330k
You have autoit.acp file 540k

- Ur file is better?
- Why readme tells "i need file in data/autocomplete". Ur file not in there.

**Comment by TomBraider42** [comment]
In CudaText the file doesn't exists, so i have created ma own and added a lot of definition to my AutoIt.acp, so its greater.  Original from Notepad++.

**Comment by Alexey-T** [comment]
so plugin must use

`dir_of_acp = os.path.dirname(__file__)`
like many plugins.

**Comment by TomBraider42** [comment]
So the AutoIt.acp will be placed in the plugin dir?
You could add it to the default Cuda package.

**Comment by Alexey-T** [comment]
Nope,please use autoit.acp from plugin folder only, using __file__

**Comment by Alexey-T** [comment]
I can put Acp to lexer zip pakg

**Comment by TomBraider42** [comment]
ok, so i can use the data/autocomplete path or change the plugin to use the local file in plugin dir?

**Comment by Alexey-T** [comment]
Local file in its dir

**Comment by TomBraider42** [comment]
now i use only the local file
