### ISSUE TITLE
Var for filename

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#6]
if os.path.isfile(os.path.join(app_path(APP_DIR_DATA), 'autocomplete', 'AutoIt.acp')):
            with open(os.path.join(app_path(APP_DIR_DATA), 'autocomplete', 'AutoIt.acp')) as fin:
 
Should be a var  (can be outside Command)

**Comment by TomBraider42** [comment]
changed
