### ISSUE TITLE
Inf event not listed

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#7]
events=on_func_hint
no autocompletion here.

So autocompl works only from Autoit lexer autoit.acp file

**Comment by Alexey-T** [comment]
pls delete file in data/... to test plugin.

**Comment by TomBraider42** [comment]
Ok, autocompletion works with autoit.acp file in data/autocomplete. Same way as in other lexers. 
Should i add functions for autocompletion to use the local acp file? Why not simply copy it to data/autocomplete?

**Comment by Alexey-T** [comment]
About plugin, pls use only file from plugin dir. Not from data...... About all, I need plugin which can do autocomplete from data/autocomplete files from any lexer, general plugin to replace my code

**Comment by TomBraider42** [comment]
added on_complete for local AutoIt.acp file
